### ISSUE TITLE
Ninja build fails

### ISSUE THREAD

**Issue by Rabidax** [Dudemanguy911/vmn#5]
Hi, me again with another build issue. `meson build` works fine after updating to 0.50.1. But now `ninja -C build` fails with the following log : 

> ninja: Entering directory `build'
> [1/1] Linking target vmn.
> FAILED: vmn 
> cc  -o vmn 'vmn@exe/src_command.c.o' 'vmn@exe/src_config.c.o' 'vmn@exe/src_library.c.o' 'vmn@exe/src_main.c.o' 'vmn@exe/src_utils.c.o' -Wl,--no-undefined -Wl,--as-needed -Wl,--start-group /usr/lib/x86_64-linux-gnu/libavformat.so /usr/lib/x86_64-linux-gnu/libavutil.so /usr/lib/x86_64-linux-gnu/libmenu.so /usr/lib/x86_64-linux-gnu/libmpv.so /usr/lib/x86_64-linux-gnu/libncurses.so /usr/lib/x86_64-linux-gnu/libtinfo.so -Wl,--end-group 
> vmn@exe/src_config.c.o : In function « vmn_set_option » :
> /home/username/repo/vmn/build/../src/config.c:531 : undefined reference to « mpv_destroy »
> vmn@exe/src_main.c.o : In function « main » :
> /home/username/repo/vmn/build/../src/main.c:171 : undefined reference to « mpv_destroy »
> collect2: error: ld returned 1 exit status
> ninja: build stopped: subcommand failed.

I have the latest ninja (1.9.0). I have libmpv-dev (0.27.2). Thanks for any help.

**Comment by Dudemanguy** [comment]
So it turns out that `mpv_destroy` actually wasn't available in mpv's client API until version 0.28. libmpv 0.27 is very old however there's no particular reason to be using `mpv_destroy` instead of `mpv_terminate_destroy` on those lines. Swapping those functions for better compatibility with old versions is no problem. It should build now with 6658e37. Thanks for the report.

**Comment by Rabidax** [comment]
0.27 is all my system's repo offers. Thanks for the compatibility effort!
